module.exports = {
  DEFAULT_NOTIFICATION_CHANNEL_NAME: '🎧 VC Notifications',
  DEFAULT_NOTIFICATION_CHANNEL_CREATION_DESCRIPTION: 'VC Notifications will appear here. Auto-generated by VC Notifier bot.',
  NOTIFICATION_CHANNEL_CREATION_MESSAGES: [
    '\nVC Notifications will appear here.',
    'This channel has been auto-generated by VC Notifier bot. If deleted, this channel will be re-created by VC Notifier bot.',
    'Feel free to change the name of this channel to whatever you wish.',

    'To change the channel in which VC Notifications appear, send a message with **!sendnotificationshere** on that channel.',
    'To receive VC notifications, send a message with **!notifyme** on any channel.',
    `To stop receiving VC notifications, send a message with **!dontnotifyme** on any channel.\n~~                                                                ~~`,
  ],
  CHANNEL_MESSAGES: {
    flags: {
      notificationSubscribe: '!notifyme',
      notificationUnsubscribe: '!dontnotifyme',
      notificationChannelSet: '!sendnotificationshere',
    },

    textMessages: {
      alreadySubscribed: 'you are already subscribed to voice chat notifications.',
      successfullySubscribed: 'you have been subscribed to voice chat notifications.',

      alreadyUnsubscribed: 'you are already not subscribed to voice chat notifications.',
      successfullyUnsubscribed: 'you have been unsubscribed from voice chat notifications.',

      alreadySetAsNotificationChannel: 'this is already the VC notifications channel.',
      successfullySetAsNotificationChannel: 'this is now the VC notifications channel.',
    },
  },
  TEMPORARILY_GOING_OFFLINE_MESSAGE: '**VC Notifier bot is temporarily going offline.** We apologize for any inconvenience.',
  BACK_ONLINE_MESSAGE: '**VC Notifier bot is online.** We apologize for any downtime and any inconvenience that may have caused.',
};
